### ISSUE TITLE
Не удается импорт модели из формата .pla

### ISSUE THREAD

**Issue by XRater** [XRater/vr-design#2]
Приложенная модель не импортируется. В консоли ошибка наличия поля root_offset у исходной модели (такое поле не было найдено).

[myproject.zip](https://github.com/XRater/vier-design/files/2480254/myproject.zip)

**Comment by XRater** [comment]
Нашел еще такой пример: 
[JanesChrystal_1XT.zip](https://github.com/XRater/vier-design/files/2480380/JanesChrystal_1XT.zip)

**Comment by AntonYermilov** [comment]
Действительно, баг воспроизводится.
Полагаю, что проблема в том, что приложенные файлы имеют формат .pla версии 1.4.3, в то время как поддержка этого формата на текущий момент реализована для более новой версии (>= 2.5.1).
Но надо проверить.

**Comment by SashaOrlova** [comment]
Решили убрать поддержку .pla формата версии меньше 1.6.8. Добавили в описание конвертируемых форматов
