### ISSUE TITLE
В логах не хватает информации о времени создания интерьера

### ISSUE THREAD

**Issue by XRater** [XRater/vr-design#9]
Создать интерьер
Просмотреть лог

Будет сообщение вида: Interior with name $name was created

Требуется сообщение: Interior with name $name was created at $time

**Comment by AntonYermilov** [comment]
Такое поведение является нормальным для нашего приложения. 
Кроме того, в логах содержится информация о времени совершаемых пользователем действий непосредственно после создания проекта. И этой информации должно быть достаточно.

**Comment by XRater** [comment]
В остальных логах время указывается. Не вижу ни одной причины не указывать его в данной ситуации.

**Comment by AntonYermilov** [comment]
Fixed.
